### ISSUE TITLE
Enhancement request: Editing crafted accessory data

### ISSUE THREAD

**Issue by NamelessMofo** [RoccoDev/recordkeeper#1]
Most of the necessary info about the location & format of the crafted accessory save data is detailed in this gbatemp thread:

https://gbatemp.net/threads/xenoblade-chronicles-3-crafted-accessory-data.628693/

All the Inoswap data is able to be edited, it would be very nice if crafted accessories could be edited as well. I don't know Rust but am willing to help however I can.

**Comment by roccodev** [comment]
This should be already implemented, both in the library and in the webapp.

If you're using the webapp, you can go to the Items page, select Accessories, then set any item to "Crafted Accessory" (you could also edit a save that already has one). When you do so, a button with a wrench icon should appear that lets you edit parameters and effect.

**Comment by NamelessMofo** [comment]
My bad, I guess in the save data crafted accessories are separate from normal ones, so I thought it would be the same in the editor. I'll give it a try. Closing.

**Comment by roccodev** [comment]
No worries, thanks again for showing interest in the project!
