### ISSUE TITLE
Enhancement: Blue Noponstone, Character order in FR Community circle

### ISSUE THREAD

**Issue by NamelessMofo** [RoccoDev/recordkeeper#2]
In an effort to help improve the project, sharing some of my findings exploring the save data format:

1. Blue Noponstone - located at 0x19afa8, looks like a uint32.
2. FR Community - while the NPC List sorting can be changed (Chronological, Name, etc.) the character portrait spiral in the main area of the screen is always sorted chronologically. Here is the info regarding how the order is built up:
- 8-Bit Flags 3853-3887 are used for this purpose.
- Each flag corresponds to a specific character.
- The value of the flag (1-35) signifies where in the order that specific character.
- Flag <-> Character encoding:
> 3853 Burrburr
3854 Jilljill
3855 Guguru
3856 Babalulu
3857 Hyzen
3858 Saomi
3859 Jethro
3860 Kayleigh
3861 Harby
3862 Hamill
3863 Lucille
3864 Lottie
3865 Georgie
3866 Mickey
3867 Miguel
3868 Lui
3869 Peridot
3870 Eow
3871 Carrom
3872 Bobobi
3873 Dillon
3874 Carsten
3875 Janus
3876 Ruben
3877 Amryn
3878 Finley
3879 Cathy
3880 Clarity
3881 Axel
3882 Cummings
3883 Searle
3884 Riku
3885 Panacea
3886 Linka
3887 Tiny Timtim

**Comment by roccodev** [comment]
I've added blue noponstone with 42f786a, it was something I had missed, thanks!

I'm afraid the FR stuff will have to wait until I'm done with gauntlet support, so I'm keeping this open until I add those.

**Comment by NamelessMofo** [comment]
Hi Rocco, just saw the commit for FR community ordering support in the web app, and I have to tell you that I really very much like your implementation. Functionally it looks like it's correct as the order matches the order in my save file, and as for the UI aspect, it's very intuitive as to how a user goes about modifying the order.

I think it would be a good idea to use a similar approach as you implement other order editing, for quests, NPCs, SH stuff, etc.

By the way, thank you again for your support and dedication for this tool, this was such a bad week with Yuzu & Lockpick both getting killed and seeing the app getting more and more features added is a ray of sunshine.

**Comment by roccodev** [comment]
Thanks for the kind words! Unfortunately, chronological data in the webapp for other sections is. Now that we have affinity and collectopedia support for FR, I'd like to add support for the respective base game features first. Then, I'd like to add menu settings like quick actions, pinned items, and active food effects.

I'll keep #3 open for the time being.
