### ISSUE TITLE
Bug: Can't edit data for challenge battle The Two Saviors

### ISSUE THREAD

**Issue by NamelessMofo** [RoccoDev/recordkeeper#6]
Game/save version: 2.1.1

Challenge battle data begins at addr 0x193ed8, which is correct. Then, an offset in the code of 0x6320 for challenge battle #19 (The Two Saviors) data is specified, which places the data at address 0x19a1f8. However, inspection of the data shows that the actual location of this data is 0x19a210.

Proposed fix: correct the offset to be 0x6338 instead.

**Comment by roccodev** [comment]
Sorry for the delay, I've fixed it in my latest push, which also adds game data for 2.2.0.
I'm quite busy at the moment, I should resume progress on updates starting mid February.
