### ISSUE TITLE
Bug: Soulhacker skill "Dodge Acceleration"

### ISSUE THREAD

**Issue by NamelessMofo** [RoccoDev/recordkeeper#8]
In a NG+ save file with all soul hacker arts & skills upgraded, I noticed that one skill shows up in the editor as not upgraded: skill 267, Dodge Acceleration. Below is screenshot, hopefully it shows up correctly.

Not sure at this point what the fix is, but I thought I should at least report it.

<img width="1195" alt="Screen Shot 2024-02-21 at 7 04 04 PM" src="https://github.com/RoccoDev/recordkeeper/assets/6599675/5c9072b0-71a4-44ae-a259-f432d006a626">

**Comment by roccodev** [comment]
It appears to have been a simple off-by-one error. Thanks!
