### ISSUE TITLE
Bug: FR enemypaedia issues

### ISSUE THREAD

**Issue by NamelessMofo** [RoccoDev/recordkeeper#9]
Decided to check out the FR enemypaedia feature on a 100% completed FR save file, and noticed two issues, one major and one minor:

1. Every entry for every monster in every region shows up as 2/N. Screenshot attached. This holds true whether it's 2/2, 2/3, 2/1 or other.
2. When, for example, on Aurora Shelf page 4, and attempting to change to another region, nothing is displayed because page 4 does not exist for those areas, e.g. Yesterdale. It might be a good idea, when changing between regions, to reset the selected page to 1.

Otherwise the layout and functionality of the feature looks pretty good, thank you and please keep up the great work!
<img width="1195" alt="Screen Shot 2024-02-25 at 5 36 07 PM" src="https://github.com/RoccoDev/recordkeeper/assets/6599675/920336b2-9230-4a3e-a314-831611a41e5f">

**Comment by roccodev** [comment]
Ah that's right, I was misled by the flag being 4-bit, and thought it would store the enemy count. The flag being 4 bits is likely an indicator that this was the case at some point during development. Instead, it stores the tri-state value for unstarted/in progress/completed. Enemy counts are in a separate section of the save file, and I had even added it to the library early on.

I'll fix the issue in the coming days. Thanks!
